#!/usr/bin/env python3
"""Assemble the formal weak-supervision training sets with group-disjoint dev splits.

This is the data the four adapters are actually trained on. It is **weak
supervision**, not human gold: Visual Genome template sentences, K400 template
sentences, Flickr candidate entities and handwritten engineering fixtures. The
manifest records each source's share, licence status and length buckets so no
result can be read as more than it is.

Split rule: whole ``group_id`` families (one image / one scene family) go to
either train or dev, never both, so paraphrases of one source cannot leak.

Usage::

    uv run --no-sync python scripts/semantic/build_formal_sets.py --name v1 --build-id formal-0001
"""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import random
import sys
from typing import Any, Iterable, Sequence

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "packages/prompt-compiler/src"))

sys.path.insert(0, str(ROOT))
from scripts.semantic.paths import DATA_ROOT, RAW_ROOT, FIXTURES_ROOT
from vbench_prompts_compile import records as R  # noqa: E402

LICENCE_NOTES = {
    "visual_genome": "CC-BY-4.0 annotations; template sentences generated by this project",
    "visual_genome_objects": "CC-BY-4.0 annotations; entity targets derived from relation endpoints",
    "k400_template": "Kinetics-400 class names; template sentences generated by this project",
    "flickr30k_entities": "LICENCE UNRESOLVED: candidates only, do not redistribute",
    "engineering_fixture": "handwritten by this project (engineering only)",
    "moviegen": "CC-BY-NC-4.0 prompt pool; no targets used",
}


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_all(paths: Iterable[Path]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for path in paths:
        if path.exists():
            rows.extend(R.read_jsonl(path))
    return rows


def collect(root: Path, task: str, build_id: str, gold_dirs: Sequence[str] = (), override_dirs: Sequence[str] = ()) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    rows += read_all([root / "data" / "processed" / build_id / "candidates" / f"{task}.jsonl"])
    rows += read_all(sorted((root / "data" / "smoke" / "local-0001").glob(f"{task}.jsonl")))
    rows += read_all(sorted((root / "data" / "processed" / build_id / "teacher").glob("candidates-*.jsonl")))
    for name in gold_dirs:
        rows += read_all([root / "data" / "gold" / name / "gold.jsonl"])
    rows = [row for row in rows if row.get("task") == task]
    unique: dict[str, dict[str, Any]] = {}
    for row in rows:
        unique.setdefault(row["sample_id"], row)
    # Override directories win over the originals for the same sample_id.
    for name in override_dirs:
        for row in read_all([root / "data" / "gold" / name / "gold.jsonl"]):
            if row.get("task") == task:
                unique[row["sample_id"]] = row
    return sorted(unique.values(), key=lambda row: row["sample_id"])


def split_by_group(rows: Sequence[dict[str, Any]], dev_fraction: float, seed: int) -> tuple[list, list]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        groups.setdefault(str(row["group_id"]), []).append(dict(row))
    ordered = sorted(groups)
    random.Random(seed).shuffle(ordered)
    dev_groups = max(1, round(len(ordered) * dev_fraction))
    dev_ids = set(ordered[:dev_groups])
    train = [row for gid in ordered if gid not in dev_ids for row in groups[gid]]
    dev = [row for gid in ordered if gid in dev_ids for row in groups[gid]]
    return train, dev


def describe(rows: Sequence[dict[str, Any]], path: Path) -> dict[str, Any]:
    return {
        "path": str(path),
        "count": len(rows),
        "sha256": sha256_file(path) if path.exists() else None,
        "groups": len({row["group_id"] for row in rows}),
        "quality_mix": dict(Counter(row["quality"] for row in rows)),
        "source_mix": dict(Counter(row["source"] for row in rows)),
        "length_buckets": dict(sorted(Counter(row.get("meta", {}).get("length_bucket", "unknown") for row in rows).items())),
        "licences": {source: LICENCE_NOTES.get(source, "unknown") for source in sorted({row["source"] for row in rows})},
    }


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--name", default="v1")
    parser.add_argument("--build-id", default="formal-0001")
    parser.add_argument("--dev-fraction", type=float, default=0.1)
    parser.add_argument("--seed", type=int, default=20260919)
    parser.add_argument("--root", default=str(ROOT / "output/paper-data"))
    parser.add_argument("--gold-dirs", default="", help="comma-separated data/gold/<name> directories to merge")
    parser.add_argument("--gold-override", default="", help="comma-separated data/gold/<name> directories whose rows replace same sample_ids")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    root = Path(args.root)
    out_dir = root / "data" / "formal" / args.name
    manifest: dict[str, Any] = {
        "name": args.name,
        "build_id": args.build_id,
        "dev_fraction": args.dev_fraction,
        "seed": args.seed,
        "split_rule": "group_id families are disjoint between train and dev",
        "data_status": "weak supervision + LLM-annotated gold (two passes + arbitration) + engineering fixtures; no human gold, see per-source licences",
        "gold_dirs": args.gold_dirs,
        "tasks": {},
    }
    for task in ("spatial", "action", "objects", "scene"):
        rows = collect(
            root,
            task,
            args.build_id,
            [name.strip() for name in args.gold_dirs.split(",") if name.strip()],
            [name.strip() for name in args.gold_override.split(",") if name.strip()],
        )
        if not rows:
            raise SystemExit(f"no records for task {task}")
        # The scene engineering fixtures only exist in data/smoke/local-0001.
        train, dev = split_by_group(rows, args.dev_fraction, args.seed)
        task_dir = out_dir / task
        train_path = task_dir / "train.jsonl"
        dev_path = task_dir / "dev.jsonl"
        R.write_jsonl(train_path, train)
        R.write_jsonl(dev_path, dev)
        manifest["tasks"][task] = {
            "total": len(rows),
            "train": describe(train, train_path),
            "dev": describe(dev, dev_path),
            "dev_group_ids": sorted({row["group_id"] for row in dev}),
        }
        print(f"{task:8} train={len(train):5} dev={len(dev):5} groups={len({row['group_id'] for row in rows})}")
    (out_dir / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"manifest: {out_dir / 'manifest.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
