#!/usr/bin/env python3
"""Build the fixed-size supplementary main table and its paper TeX view.

The script only consumes existing CSV/JSON outputs.  Missing dimensions are
represented by ``--`` and are never converted to zero.  This makes the table
safe to run before all eight dimensions have been evaluated.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import shutil
import subprocess
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DIMENSIONS = (
    ("dynamic_degree", "Dynamic Degree", "dynamics_degree"),
    ("subject_consistency", "Subject Consistency", "subject_consistency"),
    ("human_action", "Human Action", "human_action"),
    ("spatial_relationship", "Spatial Relationship", "spatial_relationship"),
    ("scene", "Scene", "scene"),
    ("multiple_objects", "Multiple Objects", "multiple_objects"),
    ("overall_consistency", "Overall Consistency", "overall_consistency"),
    ("motion_smoothness", "Motion Smoothness", "motion_smoothness"),
)


def read_csv(path: Path | None) -> list[dict[str, str]]:
    if path is None or not path.is_file():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def number(value: Any) -> float | None:
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    return result if math.isfinite(result) else None


def mean_score(path: Path, score_key: str, status_keys: tuple[str, ...]) -> tuple[float | None, int, int]:
    rows = read_csv(path)
    valid: list[float] = []
    for row in rows:
        status = next((row.get(key, "") for key in status_keys if key in row), "")
        if status not in {"success", "succeeded", "succeeded_scalar", "succeeded_structured"}:
            continue
        score = number(row.get(score_key))
        if score is not None:
            valid.append(score)
    return (sum(valid) / len(valid) if valid else None, len(valid), len(rows))


def by_dimension(rows: list[dict[str, str]]) -> dict[str, dict[str, str]]:
    return {str(row.get("dimension", "")): row for row in rows}


def metric_value(row: dict[str, str] | None) -> float | None:
    if not row:
        return None
    for key in ("test_tie_aware_acc", "test_tie_aware_accuracy", "test_acc0", "test_zero_margin_accuracy"):
        value = number(row.get(key))
        if value is not None:
            return value
    return None


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = ["dimension", "variant", "vbench_score", "human_preference"]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows({key: row.get(key, "--") for key in fields} for row in rows)


def fmt(value: Any, digits: int = 3) -> str:
    value = number(value)
    return "--" if value is None else f"{value:.{digits}f}"


def tex_escape(value: str) -> str:
    return value.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")


def write_tex(path: Path, rows: list[dict[str, Any]], metadata: dict[str, Any], width: str = "7in") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        r"% Generated by scripts/generate_supplementary_tables.py; do not hand-edit.",
        r"\documentclass[10pt,border=0pt]{standalone}",
        r"\usepackage{booktabs}",
        r"\usepackage{graphicx}",
        r"\usepackage{fontspec}",
        r"\IfFontExistsTF{Times New Roman}{\setmainfont{Times New Roman}}{\setmainfont{Nimbus Roman}}",
        r"\usepackage{array}",
        r"\begin{document}",
        rf"\resizebox{{{width}}}{{!}}{{%",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Dimension & VBench score $\uparrow$ & Human preference $\uparrow$ & Coverage $\uparrow$ \\",
        r"\midrule",
    ]
    for row in rows:
        label = tex_escape(str(row["dimension"]))
        vbench = f"{fmt(row['official_vbench_score'])}$\\to${fmt(row['repair_vbench_score'])} $\\uparrow$"
        human = f"{fmt(row['official_human_preference'])}$\\to${fmt(row['repair_human_preference'])} $\\uparrow$"
        official_coverage = fmt(row['official_coverage'] * 100 if number(row['official_coverage']) is not None else None, 1)
        repair_coverage = fmt(row['repair_coverage'] * 100 if number(row['repair_coverage']) is not None else None, 1)
        coverage = f"{official_coverage}\\%$\\to${repair_coverage}\\% $\\uparrow$"
        lines.append(f"{label} & {vbench} & {human} & {coverage} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"}", r"\end{document}", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def compile_tex(tex: Path, output_dir: Path) -> dict[str, Any]:
    compiler = shutil.which("xelatex")
    if compiler is None:
        return {"status": "blocked", "reason": "xelatex_not_found"}
    tex = tex.resolve()
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    # Compile from the output directory using the basename; passing a relative
    # path such as ``figures/table.tex`` while already cwd=figures would look
    # for the nonexistent ``figures/figures/table.tex``.
    command = [compiler, "-interaction=nonstopmode", "-halt-on-error", f"-output-directory={output_dir}", tex.name]
    result = subprocess.run(command, cwd=output_dir, text=True, capture_output=True, check=False)
    pdf = output_dir / f"{tex.stem}.pdf"
    if result.returncode != 0 or not pdf.is_file():
        return {"status": "failed", "returncode": result.returncode, "log_tail": result.stdout[-2000:]}
    png_status: dict[str, Any] = {"status": "pdf_only"}
    convert = shutil.which("pdftoppm")
    if convert:
        prefix = output_dir / tex.stem
        png_result = subprocess.run([convert, "-png", "-singlefile", "-r", "144", str(pdf), str(prefix)], text=True, capture_output=True, check=False)
        png_status = {"status": "complete" if png_result.returncode == 0 and prefix.with_suffix(".png").is_file() else "png_failed", "returncode": png_result.returncode}
    def portable(path: Path) -> str:
        try:
            return str(path.relative_to(ROOT))
        except ValueError:
            return str(path)

    return {
        "status": "complete",
        "pdf": portable(pdf),
        "png": portable(output_dir / f"{tex.stem}.png"),
        "png_status": png_status,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--official-metrics", type=Path, default=ROOT / "results/e0/e0_metrics_summary.csv")
    parser.add_argument("--repair-metrics", type=Path)
    parser.add_argument("--official-scores-root", type=Path, default=ROOT / "results/e0/raw_official_scores")
    parser.add_argument("--repair-predictions-root", type=Path)
    parser.add_argument("--output-dir", type=Path, default=ROOT / "figures")
    parser.add_argument("--no-compile", action="store_true")
    args = parser.parse_args()

    official_metrics = by_dimension(read_csv(args.official_metrics))
    repair_metrics = by_dimension(read_csv(args.repair_metrics))
    table_rows: list[dict[str, Any]] = []
    metadata: dict[str, Any] = {"schema": {"main_rows": 16, "main_columns": 4, "tex_rows": 8, "tex_columns": 4}, "dimensions": {}}
    for alias, label, official_name in DIMENSIONS:
        official_path = args.official_scores_root / official_name / "results.csv"
        off_score, off_valid, off_total = mean_score(official_path, "score", ("status",))
        rep_score = rep_valid = rep_total = None
        if args.repair_predictions_root:
            rep_path = args.repair_predictions_root / alias / "predictions.csv"
            rep_score, rep_valid, rep_total = mean_score(rep_path, "repair_score", ("repair_status", "status"))
        off_human = metric_value(official_metrics.get(alias) or official_metrics.get(official_name))
        rep_human = metric_value(repair_metrics.get(alias) or repair_metrics.get(official_name))
        off_cov = (off_valid / off_total) if off_total else None
        rep_cov = (rep_valid / rep_total) if rep_valid is not None and rep_total else None
        metadata["dimensions"][alias] = {"official_coverage": off_cov, "repair_coverage": rep_cov, "official_n": off_total, "repair_n": rep_total}
        table_rows.extend([
            {"dimension": alias, "variant": "official", "vbench_score": fmt(off_score), "human_preference": fmt(off_human)},
            {"dimension": alias, "variant": "repair", "vbench_score": fmt(rep_score), "human_preference": fmt(rep_human)},
        ])
    # The CSV intentionally has exactly the requested four columns.  TeX uses a
    # richer internal view so coverage remains visible without changing the CSV.
    main_csv = args.output_dir / "supplementary_main_table.csv"
    write_csv(main_csv, table_rows)
    tex_rows = []
    for alias, label, _ in DIMENSIONS:
        dim_meta = metadata["dimensions"][alias]
        official = next(row for row in table_rows if row["dimension"] == alias and row["variant"] == "official")
        repair = next(row for row in table_rows if row["dimension"] == alias and row["variant"] == "repair")
        tex_rows.append({"dimension": label, "official_vbench_score": official["vbench_score"], "repair_vbench_score": repair["vbench_score"], "official_human_preference": official["human_preference"], "repair_human_preference": repair["human_preference"], **dim_meta})
    tex = args.output_dir / "supplementary_main_table.tex"
    write_tex(tex, tex_rows, metadata)
    metadata["csv"] = str(main_csv)
    metadata["tex"] = str(tex)
    if not args.no_compile:
        metadata["compile"] = compile_tex(tex, args.output_dir)
    metadata_path = args.output_dir / "supplementary_main_table.metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if len(table_rows) != 16 or any(set(row) != {"dimension", "variant", "vbench_score", "human_preference"} for row in table_rows):
        raise RuntimeError("main table schema validation failed")
    print(json.dumps({"status": "COMPLETE", "csv": str(main_csv), "tex": str(tex), "metadata": str(metadata_path), "compile": metadata.get("compile", {"status": "skipped"})}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
